INSERT OR REPLACE INTO RST_FHKIF03020200_01 (
    raw_api_id,
    mrkt_div_cd, inst_cd, hour_cd, past_data_yn, fake_tick_yn, start_date, start_hour,
    base_date,
    prdy_vs, prdy_vs_sign, prdy_ctrt, prdy_clpr, prdy_idx,
    acml_vol, acml_trade_amt, kor_isnm, prpr, shrn_iscd, prdy_vol,
    mxpr, llam, oprc, hgpr, lwpr,
    prdy_oprc, prdy_hgpr, prdy_lwpr, askp, bidp,
    basis, kospi200_idx, kospi200_prdy_vs, kospi200_prdy_ctrt, kospi200_prdy_vs_sign,
    otst_stpl_qty, otst_stpl_qty_chg, today_rel_strength, thpr, disparity_rate,
    inserted_at
)
SELECT
    r.id,
    json_extract(r.param, '$.FID_COND_MRKT_DIV_CODE'),
    json_extract(r.param, '$.FID_INPUT_ISCD'),
    json_extract(r.param, '$.FID_HOUR_CLS_CODE'),
    json_extract(r.param, '$.FID_PW_DATA_INCU_YN'),
    json_extract(r.param, '$.FID_FAKE_TICK_INCU_YN'),
    json_extract(r.param, '$.FID_INPUT_DATE_1'),
    json_extract(r.param, '$.FID_INPUT_HOUR_1'),
    r.created_at,
    CAST(json_extract(r.data, '$.output1.futs_prdy_vrss') AS REAL),
    json_extract(r.data, '$.output1.prdy_vrss_sign'),
    CAST(json_extract(r.data, '$.output1.futs_prdy_ctrt') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_prdy_clpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.prdy_nmix') AS REAL),
    CAST(json_extract(r.data, '$.output1.acml_vol') AS INTEGER),
    CAST(json_extract(r.data, '$.output1.acml_tr_pbmn') AS INTEGER),
    json_extract(r.data, '$.output1.hts_kor_isnm'),
    CAST(json_extract(r.data, '$.output1.futs_prpr') AS REAL),
    json_extract(r.data, '$.output1.futs_shrn_iscd'),
    CAST(json_extract(r.data, '$.output1.prdy_vol') AS INTEGER),
    CAST(json_extract(r.data, '$.output1.futs_mxpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_llam') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_oprc') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_hgpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_lwpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_prdy_oprc') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_prdy_hgpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_prdy_lwpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_askp') AS REAL),
    CAST(json_extract(r.data, '$.output1.futs_bidp') AS REAL),
    CAST(json_extract(r.data, '$.output1.basis') AS REAL),
    CAST(json_extract(r.data, '$.output1.kospi200_nmix') AS REAL),
    CAST(json_extract(r.data, '$.output1.kospi200_prdy_vrss') AS REAL),
    CAST(json_extract(r.data, '$.output1.kospi200_prdy_ctrt') AS REAL),
    json_extract(r.data, '$.output1.kospi200_prdy_vrss_sign'),
    CAST(json_extract(r.data, '$.output1.hts_otst_stpl_qty') AS INTEGER),
    CAST(json_extract(r.data, '$.output1.otst_stpl_qty_icdc') AS INTEGER),
    CAST(json_extract(r.data, '$.output1.tday_rltv') AS REAL),
    CAST(json_extract(r.data, '$.output1.hts_thpr') AS REAL),
    CAST(json_extract(r.data, '$.output1.dprt') AS REAL),
    STRFTIME('%Y-%m-%dT%H:%M:%f', 'now')
FROM
    rst_raw_api AS r
WHERE
    r.response_type = 'FHKIF03020200' AND json_extract(r.data, '$.output1') IS NOT NULL;
;